### ISSUE TITLE
(PlatformException(Clipboard error, Unable to open clipboard, 5, null)

### ISSUE THREAD

**Issue by keith555** [leanflutter/clipboard_watcher#10]
`PlatformException (PlatformException(Clipboard error, Unable to open clipboard, 5, null))`

I'm getting this error on Windows 11 Home running the example app.  It sometimes throws the error on the first copy, sometimes after one or two successful copies. I don't know if [this](https://github.com/flutter/flutter/issues/95817) is related.

**Comment by peyman1959** [comment]
I have the same problem 
`
[        ] #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:171:7)
[        ] #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
[        ] <asynchronous suspension>
[        ] #2      Clipboard.getData (package:flutter/src/services/clipboard.dart:52:42)
[        ] <asynchronous suspension>
`

**Comment by aa2013** [comment]
> `PlatformException (PlatformException(Clipboard error, Unable to open clipboard, 5, null))`
> 
> I'm getting this error on Windows 11 Home running the example app. It sometimes throws the error on the first copy, sometimes after one or two successful copies. I don't know if [this](https://github.com/flutter/flutter/issues/95817) is related.


This error may occur when there are other applications simultaneously accessing the clipboard, and the previous program has not released the clipboard lock, resulting in inability to acquire the lock. 

I didn't use this plugin; instead, I implemented platform methods on my own and invoked them through method channel in Flutter. In the platform methods, I implemented a retry mechanism, and since then, this problem hasn't occurred again.

```c++
/*
During the window's OnCreate:

// Add clipboard monitoring, where hWndNextViewer_ is HWND
hWndNextViewer_ = SetClipboardViewer(GetHandle());

During OnDestroy:

// Remove the clipboard viewer
ChangeClipboardChain(GetHandle(), hWndNextViewer_);
*/
std::wstring ClipListenerWindow::GetClipboardText(int retry)
{
	std::wstring empty = L"";
	// 尝试打开剪贴板
	bool isOpen = OpenClipboard(nullptr);
	if (!isOpen)
	{
		if(retry >= 3)
		{
			return empty;
		}
		Sleep(100);
		return GetClipboardText(retry + 1);
	}

	// 尝试获取剪贴板中的数据
	HANDLE hData = GetClipboardData(CF_UNICODETEXT);
	if (hData == nullptr)
	{
		CloseClipboard();
		return empty;
	}

	// 锁定内存并获取数据
	wchar_t* pszText = static_cast<wchar_t*>(GlobalLock(hData));
	if (pszText == nullptr)
	{
		CloseClipboard();
		return empty;
	}

	// 复制数据到字符串
	std::wstring clipboardText(pszText);

	// 释放内存和关闭剪贴板
	GlobalUnlock(hData);
	CloseClipboard();

	return clipboardText;
}

LRESULT ClipListenerWindow::MessageHandler(HWND hwnd, UINT const uMsg, WPARAM const wParam,
                                           LPARAM const lParam) noexcept
{
	// hwnd: 表示窗口的句柄（handle），是消息发送或接收的窗口的标识符。在函数内，您可以使用这个句柄与窗口进行交互。
	//
	// uMsg : 表示窗口消息的标识符。它指定了要处理的消息类型。例如，WM_DRAWCLIPBOARD 表示剪贴板内容发生变化的消息。
	// WM_DRAWCLIPBOARD 中，wParam 和 lParam 分别表示剪贴板触发事件的原因和相关的句柄。
	//
	// 	wParam : 通常用于传递一些消息相关的信息，如通知消息的原因、按下的键值等。
	//
	// 	lParam : 通常用于传递指针或句柄，指向消息相关的数据结构或对象。

	std::string s("listener handle: " + std::to_string(uMsg) + "\n");
	std::wstring wideString(s.begin(), s.end());
	OutputDebugString(wideString.c_str());
	switch (uMsg)
	{
	case WM_DRAWCLIPBOARD:
		{
			// 剪贴板内容发生变化
			// 处理剪贴板变化的代码可以放在这里
			std::wstring text = GetClipboardText();
			if (!text.empty() && text != lastText)
				SendClip(text);
			lastText = text;
			// 转发消息给下一个剪贴板查看器
			SendMessage(hWndNextViewer_, WM_DRAWCLIPBOARD, wParam, lParam);
		}
		break;
	case WM_CHANGECBCHAIN:
		{
			// 处理剪贴板链的变化
			if ((HWND)wParam == hWndNextViewer_)
				hWndNextViewer_ = (HWND)lParam;
			else if (hWndNextViewer_ != nullptr)
				SendMessage(hWndNextViewer_, uMsg, wParam, lParam);
		}
		break;
	}

	return Win32Window::MessageHandler(hwnd, uMsg, wParam, lParam);
}

```

**Comment by aa2013** [comment]
> `PlatformException (PlatformException(Clipboard error, Unable to open clipboard, 5, null))`
> 
> I'm getting this error on Windows 11 Home running the example app. It sometimes throws the error on the first copy, sometimes after one or two successful copies. I don't know if [this](https://github.com/flutter/flutter/issues/95817) is related.

This error may occur when there are other applications simultaneously accessing the clipboard, and the previous program has not released the clipboard lock, resulting in inability to acquire the lock.

**Comment by aa2013** [comment]
You can independently implement the corresponding platform method and then add a delayed retry mechanism, which can basically eliminate the problem
